an:
  frontpage: 89
  help docs: 9
  main: 90
ar:
  frontpage: 89
  help docs: 8
  main: 50
be-BY:
  frontpage: 100
  help docs: 11
  main: 93
bg-BG:
  frontpage: 15
  help docs: 2
  main: 42
ca:
  frontpage: 84
  help docs: 7
  main: 76
cmn:
  frontpage: 2
  help docs: 1
  main: 30
cs:
  frontpage: 97
  help docs: 8
  main: 79
da:
  frontpage: 89
  help docs: 9
  main: 89
de:
  frontpage: 100
  help docs: 50
  main: 97
el:
  frontpage: 100
  help docs: 46
  main: 97
eo:
  frontpage: 89
  help docs: 9
  main: 88
es:
  frontpage: 100
  help docs: 64
  main: 100
fa-IR:
  frontpage: 89
  help docs: 1
  main: 14
fi:
  frontpage: 0
  help docs: 0
  main: 7
fr:
  frontpage: 100
  help docs: 28
  main: 99
ga-IE:
  frontpage: 43
  help docs: 4
  main: 44
gl:
  frontpage: 48
  help docs: 8
  main: 69
he:
  frontpage: 92
  help docs: 8
  main: 65
hi:
  frontpage: 0
  help docs: 0
  main: 1
hr:
  frontpage: 100
  help docs: 15
  main: 47
hu:
  frontpage: 100
  help docs: 77
  main: 98
id:
  frontpage: 48
  help docs: 2
  main: 54
it:
  frontpage: 100
  help docs: 9
  main: 90
it-CH:
  frontpage: 0
  help docs: 0
  main: 0
ja:
  frontpage: 76
  help docs: 4
  main: 63
km:
  frontpage: 12
  help docs: 2
  main: 50
ko:
  frontpage: 89
  help docs: 3
  main: 57
lv:
  frontpage: 0
  help docs: 0
  main: 0
mi:
  frontpage: 2
  help docs: 0
  main: 4
mk:
  frontpage: 89
  help docs: 3
  main: 55
ml:
  frontpage: 15
  help docs: 3
  main: 53
ml-IN:
  frontpage: 0
  help docs: 0
  main: 0
nl-NL:
  frontpage: 100
  help docs: 51
  main: 94
pl:
  frontpage: 89
  help docs: 1
  main: 18
pt-BR:
  frontpage: 100
  help docs: 100
  main: 100
pt-PT:
  frontpage: 28
  help docs: 0
  main: 9
ro:
  frontpage: 89
  help docs: 9
  main: 90
ru:
  frontpage: 100
  help docs: 8
  main: 64
sk:
  frontpage: 89
  help docs: 9
  main: 90
sl:
  frontpage: 100
  help docs: 11
  main: 93
sr:
  frontpage: 100
  help docs: 11
  main: 96
sr-RS:
  frontpage: 100
  help docs: 11
  main: 96
sv:
  frontpage: 89
  help docs: 9
  main: 89
te:
  frontpage: 25
  help docs: 2
  main: 29
tr:
  frontpage: 89
  help docs: 9
  main: 90
uk:
  frontpage: 100
  help docs: 8
  main: 77
ur:
  frontpage: 0
  help docs: 0
  main: 0
ur-PK:
  frontpage: 0
  help docs: 0
  main: 0
vi:
  frontpage: 12
  help docs: 2
  main: 45
zh-TW:
  frontpage: 100
  help docs: 48
  main: 100
